import { useState } from 'react';
import { content, links, type Language } from '../content/site';
import { Arrow } from '../components/Arrow';
const ids = ['leistungen', 'arbeiten', 'ueber-mich', 'kontakt'];
export function Home({ lang }: { lang: Language }) {
 const c = content[lang];
 const [open, setOpen] = useState(false);
 const base = import.meta.env.BASE_URL;
 return <>
  <a href="#main" className="skip-link">{c.skip}</a>
  <header className="header wrap" onKeyDown={e => { if (e.key === 'Escape' && open) { setOpen(false); document.querySelector<HTMLButtonElement>('.menu-toggle')?.focus(); } }}>
   <a href={base + (lang === 'en' ? 'en/' : '')} className="brand" aria-label="NikVisuals — Home">nikvisuals<span className="brand-mark" aria-hidden="true">.</span></a>
   <nav className="desktop-nav" aria-label={lang === 'de' ? 'Hauptnavigation' : 'Main navigation'}>{c.nav.slice(0, 3).map((n, i) => <a href={'#' + ids[i]} key={n}>{n}</a>)}</nav>
   <div className="header-end"><nav className="languages" aria-label={c.language}><a href={base} hrefLang="de" lang="de" aria-current={lang === 'de' ? 'page' : undefined}>DE</a><span>/</span><a href={base + 'en/'} hrefLang="en" lang="en" aria-current={lang === 'en' ? 'page' : undefined}>EN</a></nav><a className="header-contact" href="#kontakt">{c.nav[3]}<Arrow diagonal /></a><button className="menu-toggle" aria-expanded={open} aria-controls="mobile-nav" onClick={() => setOpen(!open)}>{open ? c.close : c.menu}<span aria-hidden="true">{open ? '−' : '+'}</span></button></div>
   <nav id="mobile-nav" className="mobile-nav" hidden={!open} aria-label={lang === 'de' ? 'Mobile Navigation' : 'Mobile navigation'}>{c.nav.map((n, i) => <a href={'#' + ids[i]} key={n} onClick={() => setOpen(false)}>{n}<Arrow /></a>)}</nav>
  </header>
  <main id="main">
   <section className="hero wrap" aria-labelledby="hero-title">
    <p className="eyebrow hero-eyebrow"><span className="small-cross" aria-hidden="true">✳</span>{c.eyebrow}</p>
    <h1 id="hero-title"><span>{c.headline}</span><span className="hero-secondary">{c.headlineEnd}</span></h1>
    <div className="hero-bottom"><div className="founder-line"><span className="founder-monogram" aria-hidden="true">nb.</span><p>NikVisuals<span>by Niklas Brüne</span></p></div><div className="hero-detail"><p>{c.intro}</p><div className="hero-actions"><a href="#kontakt" className="button">{c.cta}<Arrow diagonal /></a><a href="#arbeiten" className="text-link">{c.workCta}<Arrow /></a></div></div></div>
   </section>
   <section id="leistungen" className="services section" aria-labelledby="services-title"><div className="wrap"><div className="section-heading"><p className="eyebrow">{c.serviceLabel}</p><h2 id="services-title">{c.serviceTitle}</h2></div><div className="service-grid">{c.services.map((s, i) => <article className="service" key={s.name}><span className="service-index">0{i+1}</span><h3>{s.name}</h3><p>{s.text}</p><ul>{s.tags.map(t => <li key={t}>{t}</li>)}</ul></article>)}</div><aside className="bridge"><p className="eyebrow">{c.bridgeLabel}</p><p>{c.bridge}</p></aside></div></section>
   <section id="arbeiten" className="work section wrap" aria-labelledby="work-title"><div className="work-heading"><div><p className="eyebrow">{c.workLabel}</p><h2 id="work-title">{c.workTitle}</h2></div><p>{c.workIntro}</p></div><div className="case-grid">{c.cases.map((p, i) => <article className={'case case-' + p.type} key={p.name}>{p.image ? <a className="case-visual photo" href={p.video} target="_blank" rel="noreferrer" aria-label={`${p.name}: ${c.video}`}><img src={base + 'images/' + p.image} alt={p.alt} width="1280" height="720" loading="lazy" decoding="async"/><span className="play"><svg aria-hidden="true" width="15" height="18" viewBox="0 0 15 18"><path d="m1 1 13 8-13 8z" fill="currentColor" /></svg></span><span className="film-caption">{c.video}<Arrow diagonal /></span></a> : <div className={'case-visual art ' + p.type} aria-label={`${p.name}: ${c.artwork}`}><span className="art-caption">{p.category}</span><span className="art-title">{c.artTitles[p.type === 'industrial' ? 0 : 1]}</span><span className="art-footer">{c.artwork}<span aria-hidden="true">0{i+1}</span></span></div>}<div className="case-meta"><h3>{p.name}</h3><span>{p.category}</span></div><p className="case-description">{p.text}</p></article>)}</div></section>
   <section id="ueber-mich" className="about section" aria-labelledby="about-title"><div className="wrap about-grid"><figure><img src={base + 'images/behind-the-scenes.jpg'} width="1200" height="675" alt={c.aboutAlt} loading="lazy" decoding="async"/><figcaption>{c.aboutCaption}</figcaption></figure><div className="about-copy"><p className="eyebrow">{c.aboutLabel}</p><h2 id="about-title">{c.aboutTitle}</h2><p>{c.about}</p><p className="about-signal">{c.aboutSignal}</p></div></div></section>
   <section id="kontakt" className="contact section" aria-labelledby="contact-title"><div className="wrap"><p className="eyebrow">{c.contactLabel}</p><a className="contact-heading" href={links.email}><h2 id="contact-title">{c.contactTitle}<span>.</span></h2><Arrow diagonal /></a><div className="contact-bottom"><p>{c.contactText}</p><a className="email" href={links.email}>info@nikvisuals.de<Arrow diagonal /></a></div></div></section>
  </main>
  <footer className="footer wrap"><div className="footer-top"><a className="brand" href={base + (lang === 'en' ? 'en/' : '')}>nikvisuals</a><span>{c.footer}</span><div className="socials">{links.socials.map(l => <a key={l.label} href={l.href} target="_blank" rel="noreferrer">{l.label}<Arrow diagonal /></a>)}</div></div><div className="footer-bottom"><span>{c.preview}</span><a href="https://www.nikvisuals.de/impressum" target="_blank" rel="noreferrer">{c.legal}<Arrow diagonal /></a></div><details className="privacy"><summary>{c.privacy}</summary><p>{c.privacyText} <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noreferrer">{c.githubPrivacy}<Arrow diagonal /></a></p></details></footer>
 </>;
}
