import { useEffect, useState } from 'react';
import { content, links, type Language } from '../content/site';
import { Arrow } from '../components/Arrow';

export function Links({ lang }: { lang: Language }) {
  const c = content[lang]; const base = import.meta.env.BASE_URL; const home = base + (lang === 'en' ? 'en/' : '');
  const [theme, setTheme] = useState<'light' | 'dark'>('light'); const [ready, setReady] = useState(false);
  useEffect(() => { const saved = localStorage.getItem('nikvisuals-theme'); setTheme(saved === 'dark' || (!saved && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'); setReady(true); }, []);
  useEffect(() => { if (!ready) return; document.documentElement.dataset.theme = theme; localStorage.setItem('nikvisuals-theme', theme); }, [ready, theme]);
  const primary = [{ label: c.hub.website, href: home }, { label: c.hub.project, href: home + '#kontakt' }]; const next = theme === 'dark' ? 'light' : 'dark';
  return <main className="link-hub"><div className="link-hub-inner"><div className="hub-top"><a className="brand" href={home}>nikvisuals<span className="brand-mark">.</span></a><button className="theme-toggle" type="button" aria-label={next === 'dark' ? c.darkMode : c.lightMode} onClick={() => setTheme(next)}><span aria-hidden="true">{theme === 'dark' ? '☀' : '◐'}</span></button></div><div className="hub-profile"><img src={base + 'images/niklas-current-profile.webp'} width="1800" height="1800" alt={c.hub.hubPortraitAlt}/><p className="eyebrow">{c.hub.eyebrow}</p><h1>{c.hub.title}</h1><p>{c.hub.intro}</p></div><nav className="hub-links" aria-label="Links">{primary.map((item: { label: string; href: string }) => <a className="hub-link hub-link-primary" href={item.href} key={item.label}>{item.label}<Arrow diagonal/></a>)}<span className="hub-label">{c.hub.socials}</span>{links.socials.map((item: { label: string; href: string }) => <a className="hub-link" href={item.href} target="_blank" rel="noreferrer" key={item.label}>{item.label}<Arrow diagonal/></a>)}<a className="hub-link" href="https://www.facebook.com/nikvisualsmedia" target="_blank" rel="noreferrer">Facebook<Arrow diagonal/></a><a className="hub-link" href="https://www.amazon.de/shop/nikvisuals" target="_blank" rel="noreferrer">{c.hub.gear}<Arrow diagonal/></a><span className="hub-label">{c.hub.contact}</span><a className="hub-link" href={links.email}>info@nikvisuals.de<Arrow diagonal/></a><a className="hub-link" href={links.phone}>{c.hub.phone}: +49 176 55263773<Arrow diagonal/></a></nav><footer className="hub-footer"><a href="https://www.nikvisuals.de/impressum" target="_blank" rel="noreferrer">{c.hub.legal}</a><a href={home + '#datenschutz'}>{c.hub.privacy}</a><a href={lang === 'de' ? base + 'en/links/' : base + 'links/'} hrefLang={lang === 'de' ? 'en' : 'de'}>{lang === 'de' ? 'English' : 'Deutsch'}</a></footer></div></main>;
}
