import { useEffect, useState } from 'react';
import { content, links, type Language } from '../content/site';
import { Arrow } from '../components/Arrow';
import { CopyEmailButton } from '../components/CopyEmailButton';
import { SiteFooter } from '../components/SiteFooter';
import { ThemeIcon } from '../components/ThemeIcon';
import { SocialIcon } from '../components/SocialIcon';

export function Links({ lang }: { lang: Language }) { const c = content[lang], base = import.meta.env.BASE_URL, home = base + (lang === 'en' ? 'en/' : ''); const [theme, setTheme] = useState<'light' | 'dark'>('dark'); useEffect(() => setTheme(localStorage.getItem('nikvisuals-theme') === 'light' ? 'light' : 'dark'), []); useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('nikvisuals-theme', theme); document.querySelector('meta[name="theme-color"]')?.setAttribute('content', theme === 'light' ? '#f7f5ef' : '#131419'); }, [theme]); const next = theme === 'dark' ? 'light' : 'dark'; const primary = [{ label: c.hub.website, href: home }, { label: c.hub.project, href: home + '#kontakt' }]; return <><main className="link-hub"><div className="link-hub-inner"><div className="hub-top"><a className="brand" href={home}>nikvisuals<span className="brand-mark">.</span></a><button className="theme-toggle" type="button" aria-label={next === 'dark' ? c.darkMode : c.lightMode} onClick={() => setTheme(next)}><ThemeIcon light={theme === 'dark'} /></button></div><div className="hub-profile"><img src={base + 'images/niklas-current-profile.webp'} width="1800" height="1800" alt={c.hub.hubPortraitAlt} /><p className="eyebrow">{c.hub.eyebrow}</p><h1>{c.hub.title}</h1><p>{c.hub.intro}</p></div><nav className="hub-links" aria-label="Links">{primary.map(item => <a className="hub-link hub-link-primary" href={item.href} key={item.label}>{item.label}<Arrow diagonal /></a>)}<span className="hub-label">{c.hub.socials}</span>{links.socials.map(item => <a className="hub-link hub-link-social" href={item.href} target="_blank" rel="noreferrer" key={item.label}><span className="hub-social-label"><SocialIcon platform={item.platform} />{item.label}</span><Arrow diagonal /></a>)}<a className="hub-link" href="https://www.amazon.de/shop/nikvisuals" target="_blank" rel="noreferrer">{c.hub.gear}<Arrow diagonal /></a><span className="hub-label">{c.hub.contact}</span><div className="hub-email"><a href={links.email}>info@nikvisuals.de<Arrow diagonal /></a><CopyEmailButton lang={lang} className="hub-copy" /></div></nav></div></main><SiteFooter lang={lang} /></>; }
