import { content, links, type Language } from '../content/site';
import { videoSections, type Video } from '../content/videos';
import { Arrow } from '../components/Arrow';
import { PlayIcon } from '../components/PlayIcon';
import { SocialIcon } from '../components/SocialIcon';
import { useMediaConsent } from '../components/MediaConsent';

function VideoCard({ video, lang, section }: { video: Video; lang: Language; section: string }) { const c = content[lang], base = import.meta.env.BASE_URL, { playVideo } = useMediaConsent(); return <article className="video-card"><div className="video-thumb"><img src={base + 'images/' + video.thumbnail} alt={video.thumbnailAlt[lang]} width="640" height="360" loading="lazy" decoding="async" /><span className="play" data-thumbnail-play aria-hidden="true"><PlayIcon /></span></div><div className="video-card-body"><p className="video-category">{section}{video.organization ? ` · ${video.organization}` : ''}</p><h3>{video.displayTitle[lang]}</h3><p className="video-summary">{video.summary[lang]}</p><div className="video-actions"><button type="button" className="video-open" onClick={event => playVideo({id:video.id,title:video.displayTitle[lang],trigger:event.currentTarget})}><PlayIcon />{lang === 'de' ? 'Hier ansehen' : 'Watch here'}</button><a className="video-open" href={`https://www.youtube.com/watch?v=${video.id}`} target="_blank" rel="noreferrer"><SocialIcon platform="youtube" />{c.videoPage.open}<Arrow diagonal /></a></div></div></article>; }

export function Videos({ lang }: { lang: Language }) { const c = content[lang], base = import.meta.env.BASE_URL, home = base + (lang === 'en' ? 'en/' : ''); return <main className="videos-page"><header className="videos-header"><div className="wrap"><a className="brand" href={home}>nikvisuals<span className="brand-mark">.</span></a><nav><a href={home}>{c.videoPage.back}</a><a href={lang === 'de' ? base + 'en/videos/' : base + 'videos/'}>{c.videoPage.language}</a></nav></div></header><section className="videos-hero"><div className="wrap videos-hero-content"><p className="eyebrow">{c.videoPage.eyebrow}</p><h1>{c.videoPage.title}</h1><p>{c.videoPage.intro}</p><nav className="video-jumps" aria-label={lang === 'de' ? 'Videokategorien' : 'Video categories'}>{videoSections.map(section => <a key={section.id} href={'#video-' + section.id}>{section.title[lang]}</a>)}</nav></div></section><section className="videos-grid-section"><div className="wrap">{videoSections.map(section => <section className="video-section" id={'video-' + section.id} key={section.id}><h2>{section.title[lang]}</h2><div className="videos-grid">{section.items.map(video => <VideoCard video={video} lang={lang} section={section.title[lang]} key={video.id} />)}</div></section>)}<a className="videos-channel" href={links.youtube} target="_blank" rel="noreferrer">YouTube · nikvisualsmedia<Arrow diagonal /></a></div></section></main>; }
