export type Language = 'de' | 'en';

export const links = { email: 'mailto:info@nikvisuals.de', phone: 'tel:+4917655263773', website: 'https://www.nikvisuals.de/', socials: [
  { label: 'LinkedIn', href: 'https://www.linkedin.com/in/niklas-br%C3%BCne-b61877243/' }, { label: 'Instagram', href: 'https://www.instagram.com/nikvisualsmedia/' }, { label: 'YouTube', href: 'https://www.youtube.com/@nikvisualsmedia/' },
] };

const cases = [
  { name: 'LapStore', image: 'lapstore.jpg', logo: 'lapstore-logo.png', video: 'https://www.youtube.com/watch?v=hWaSx8RWAg8' },
  { name: 'SMS group', image: 'sms-group-event.webp', logo: 'sms-group-logo.png', video: '' },
  { name: 'Stadt Hilchenbach', image: 'hilchenbach.jpg', logo: 'hilchenbach-logo.png', video: 'https://www.youtube.com/watch?v=5iZrmH-16NY' },
  { name: 'IHK Siegen', image: 'ihk-workshop-2026.webp', logo: '', video: '', portrait: true },
];
const collaborators = cases.map(({ name, logo }) => ({ name, logo })).concat([{ name: 'Startpunkt57', logo: '' }, { name: 'Entrepreneurship Center Siegen', logo: '' }]);
const deCases = cases.map((item, i) => ({ ...item, category: ['Content + Business Development', 'Corporate Media', 'Content & Distribution', 'Workshops'][i], text: [
  'Für LapStore entstand über viele Jahre Produkt-Content. Später kamen Wettbewerbsresearch, B2B-Strategie und Business Development hinzu.',
  'Für SMS group entstanden wiederholt Corporate-, Industrie- und Eventproduktionen. Die Projekte erforderten komplexe Abstimmung und zum Teil kurze Lieferzeiten.',
  'Für die Stadt Hilchenbach entstand über mehrere Jahre Drohnen- und Content-Material für Tourismus und Stadtmarketing. Dazu kamen Social Media und Distribution. Die Inhalte erreichten organisch Menschen und wurden regional medial aufgegriffen.',
  'Praxisnahe Workshops zu Social Media, Content und Smartphone-Video für den direkten Einsatz im Arbeitsalltag.',
][i], alt: ['Szene aus einem LapStore-Werbevideo: ein Mann mit Smartphone.', 'Bühne bei einer SMS-group-Veranstaltung.', 'Luftaufnahme von Hilchenbach aus dem NikVisuals-Drohnenfilm.', 'Niklas Brüne bei einem IHK-Siegen-Workshop am 19. Mai 2026.'][i] }));
const enCases = cases.map((item, i) => ({ ...item, category: ['Content + Business Development', 'Corporate Media', 'Content & Distribution', 'Workshops'][i], text: [
  'Product content for LapStore over several years. Competitor research, B2B strategy and business development followed later.',
  'Repeated corporate, industrial and event productions for SMS group. The work involved complex coordination and, at times, short delivery timelines.',
  'Several years of drone and content work for tourism and city marketing in Hilchenbach, followed by social media and distribution. The content reached people organically and received regional media attention.',
  'Practical workshops on social media, content and smartphone video for direct use in day-to-day work.',
][i], alt: ['Scene from a LapStore advertising film: a man using a smartphone.', 'Stage at an SMS group event.', 'Aerial view of Hilchenbach from the NikVisuals drone film.', 'Niklas Brüne at an IHK Siegen workshop on 19 May 2026.'][i] }));

export const content = {
  de: {
    skip: 'Zum Inhalt', menu: 'Menü', close: 'Schließen', language: 'Sprache wählen', nav: ['Schwerpunkte', 'Arbeiten', 'Über mich', 'Kontakt'],
    eyebrow: 'NikVisuals by Niklas Brüne', headline: 'AI, Growth & Marketing', headlineEnd: 'für ambitionierte B2B-Unternehmen.', intro: 'Ich unterstütze ausgewählte B2B-Projekte bei Research, Strategie und der praktischen Umsetzung mit bestehenden Tools – von Workflows bis zu Content-Systemen.', cta: 'Projekt besprechen', workCta: 'Arbeiten ansehen', heroNote: 'NikVisuals by Niklas Brüne', heroMediaLabel: 'Niklas Brüne, Gründer von NikVisuals', heroMediaAlt: 'Porträt von Niklas Brüne im Freien.',
    serviceLabel: '01 / Schwerpunkte', serviceTitle: 'Schwerpunkte', services: [
      { name: 'AI & Prozesse', text: 'Ich prüfe, wo AI im Arbeitsalltag sinnvoll helfen kann – etwa bei Research, Wissensarbeit und wiederkehrenden Abläufen. Dafür nutze ich vorhandene Tools.', tags: ['AI-Use-Cases', 'Research & Wissensarbeit', 'Workflows & Automatisierung'] },
      { name: 'Growth, GTM &\nBusiness Development', text: 'Ich unterstütze bei Markt- und Wettbewerbsresearch, GTM-Ansätzen und Business Development. Angebote und neue Märkte werden früh geprüft.', tags: ['Markt- & Wettbewerbsresearch', 'Go-to-Market', 'Business Development'] },
      { name: 'Marketing & Content', text: 'Ich helfe Teams, Marketing und Content klarer zu organisieren. Dazu gehören Strategie, Content- und Social-Prozesse sowie ausgewählte Produktion.', tags: ['Marketingstrategie', 'Content- & Social-Systeme', 'Ausgewählte Produktion'] },
    ],
    bridgeLabel: 'Hintergrund', bridgeTitle: 'Selbstständig seit 2021.', bridge: 'Kundenarbeit, Studium und fachliche Arbeit zu AI im digitalen Marketing gehören zusammen.', markers: [{ title: 'Seit 2021', text: 'selbstständig / Kundenprojekte' }, { title: 'Universität Siegen', text: 'M.Sc. Entrepreneurship & SME Management' }, { title: 'University of Tulsa', text: 'Business Exchange' }],
    workLabel: '02 / Bisherige Projekte', workTitle: 'Vier ausgewählte\nProjekte.', workIntro: 'Die folgenden Projekte stammen aus Media, Content, Workshops und Business Development.', video: 'Film auf YouTube ansehen', cases: deCases, collaborationTitle: 'Bisherige Zusammenarbeit', collaborationSubtitle: 'Media, Content, Workshops & Business Development', collaborators,
    proofLabel: 'Aus früheren Kunden- und Projektbewertungen', proofTitle: 'Was Kunden sagen', rating: '5,0 / 5', reviews: '49 Google-Bewertungen', reviewNote: 'Zusammenfassungen des Kundenfeedbacks aus früheren Projekten.', testimonials: [
      { name: 'Steffen Kellermann', role: 'Bezirksschornsteinfeger & Energieberater', text: 'Steffen Kellermann hebt die strukturierte und entspannte Begleitung hervor. Auch ohne Erfahrung mit Videoproduktion wusste er jederzeit, was als Nächstes passiert. Das fertige Video hat seine Erwartungen deutlich übertroffen.' },
      { name: 'Frank Vorländer', role: 'Sanitär- und Heizungsbaubetrieb', text: 'Frank Vorländer beschreibt die Abstimmung als unkompliziert und zuverlässig. Wichtig waren für ihn das professionelle Auftreten, eingehaltene Zeitpläne und ein Film, der zu seinem Betrieb passt.' },
      { name: 'Kerstin Broh', role: 'Stadt Hilchenbach / Tourismus & Stadtmarketing', text: 'Kerstin Broh beschreibt die Zusammenarbeit als professionell, reibungslos und termintreu. Durch die gemeinsame Veröffentlichung entstand zusätzlich organische Reichweite und regionale Medienresonanz.' },
    ], videoFeedback: 'Video-Feedback von Kerstin Broh ansehen',
    aboutLabel: '03 / Über mich', aboutTitle: 'Hi, ich bin Niklas.', about: 'Ich komme aus der Video- und Content-Produktion. Heute arbeite ich mit B2B- und Unternehmenskunden an Marketing, Business Development und dem praktischen Einsatz von AI.', aboutCaption: 'Niklas Brüne', aboutSignal: 'Auch vorgestellt bei WDR Lokalzeit & Radio Siegen',
    contactLabel: '04 / Kontakt', contactTitle: 'Projekt besprechen', contactText: 'Hast du eine Idee, eine Frage oder eine konkrete Herausforderung? Schreib kurz, worum es geht.', form: { name: 'Name', email: 'E-Mail', company: 'Unternehmen', message: 'Worum geht es?', consentBefore: 'Ich habe die ', privacy: 'Datenschutz-Hinweise', consentAfter: ' gelesen.', submit: 'Anfrage senden', note: 'Vorschau ohne Versand', error: 'Bitte fülle alle Pflichtfelder korrekt aus.', preview: 'In dieser Vorschau wird nichts versendet. Schreib mir direkt an' },
    emailLabel: 'E-Mail schreiben', footer: 'by Niklas Brüne', preview: 'Vorschau · Nicht zur Indexierung', legal: 'Impressum (bestehende Website)', privacy: 'Datenschutz dieser Vorschau', privacyTitle: 'Datenschutz der Vorschau', privacyText: 'Diese Vorschau verwendet keine Analyse-Tools, Cookies oder eingebetteten Drittanbieter-Medien. Die lokale Formularoberfläche überträgt oder speichert keine Eingaben. GitHub Pages stellt die Website bereit und kann technische Zugriffsdaten verarbeiten. Externe Links öffnen erst nach einem Klick die jeweilige Website. Bei Kontakt per E-Mail werden die übermittelten Angaben zur Bearbeitung der Anfrage verwendet. Verantwortlich: Niklas Brüne; Kontaktdaten im verlinkten Impressum.', githubPrivacy: 'Datenschutzerklärung von GitHub',
    hub: { eyebrow: 'NikVisuals', title: 'Niklas Brüne', intro: 'Website, Social Media und Kontakt.', website: 'Website', project: 'Projekt besprechen', socials: 'Social Media', gear: 'Meine Ausrüstung', contact: 'Kontakt', phone: 'Telefon', legal: 'Impressum', privacy: 'Datenschutz' },
  },
  en: {
    skip: 'Skip to content', menu: 'Menu', close: 'Close', language: 'Choose language', nav: ['Focus', 'Work', 'About', 'Contact'],
    eyebrow: 'NikVisuals by Niklas Brüne', headline: 'AI, Growth & Marketing', headlineEnd: 'for ambitious B2B companies.', intro: 'I support selected B2B projects with research, strategy and practical delivery using existing tools – from workflows to content systems.', cta: 'Discuss a project', workCta: 'View projects', heroNote: 'NikVisuals by Niklas Brüne', heroMediaLabel: 'Niklas Brüne, founder of NikVisuals', heroMediaAlt: 'Portrait of Niklas Brüne outdoors.',
    serviceLabel: '01 / Focus areas', serviceTitle: 'Focus areas', services: [
      { name: 'AI & Processes', text: 'I assess where AI can be useful in day-to-day work: research, knowledge work and recurring tasks. The work builds on tools already in place.', tags: ['AI use cases', 'Research & knowledge work', 'Workflows & automation'] },
      { name: 'Growth, GTM &\nBusiness Development', text: 'I support market and competitor research, GTM work and business development. Offers and new markets are tested early.', tags: ['Market & competitor research', 'Go-to-market', 'Business development'] },
      { name: 'Marketing & Content', text: 'I help teams organise marketing and content more clearly, including strategy, content and social processes, and selected production.', tags: ['Marketing strategy', 'Content & social systems', 'Selected production'] },
    ],
    bridgeLabel: 'Background', bridgeTitle: 'Independent since 2021.', bridge: 'Client work sits alongside my studies and academic work on AI in digital marketing.', markers: [{ title: 'Since 2021', text: 'independent / client projects' }, { title: 'University of Siegen', text: 'M.Sc. Entrepreneurship & SME Management' }, { title: 'University of Tulsa', text: 'Business Exchange' }],
    workLabel: '02 / Previous projects', workTitle: 'Four selected\nprojects.', workIntro: 'These projects cover media, content, workshops and business development.', video: 'Watch film on YouTube', cases: enCases, collaborationTitle: 'Previous collaborations', collaborationSubtitle: 'Media, content, workshops & business development', collaborators,
    proofLabel: 'From earlier client and project reviews', proofTitle: 'What clients say', rating: '5.0 / 5', reviews: '49 Google reviews', reviewNote: 'Summaries of customer feedback from earlier projects.', testimonials: [
      { name: 'Steffen Kellermann', role: 'Master chimney sweep & energy consultant', text: 'Steffen Kellermann values the structured, low-pressure support throughout the process. Even without video-production experience, he always knew what would happen next. The finished video exceeded his expectations.' },
      { name: 'Frank Vorländer', role: 'Plumbing and heating business', text: 'Frank Vorländer found the communication straightforward and reliable. He particularly valued the professional approach, the kept timelines and a film that suited his business.' },
      { name: 'Kerstin Broh', role: 'Stadt Hilchenbach / tourism & city marketing', text: 'Kerstin Broh describes the work as professional, smooth and on schedule. Publishing the content together also generated organic reach and regional media attention.' },
    ], videoFeedback: 'Watch Kerstin Broh’s video feedback',
    aboutLabel: '03 / About', aboutTitle: 'Hi, I’m Niklas.', about: 'My background is in video and content production. Today I work with B2B and corporate clients on marketing, business development and practical uses of AI.', aboutCaption: 'Niklas Brüne', aboutSignal: 'Also featured on WDR Lokalzeit & Radio Siegen',
    contactLabel: '04 / Contact', contactTitle: 'Discuss a project', contactText: 'Have an idea, a question or a specific challenge? Briefly describe what it is about.', form: { name: 'Name', email: 'Email', company: 'Company', message: 'What is it about?', consentBefore: 'I have read the ', privacy: 'privacy notice', consentAfter: '.', submit: 'Send enquiry', note: 'Preview only — nothing is sent', error: 'Please complete all required fields correctly.', preview: 'Nothing is sent from this preview. Please email me directly at' },
    emailLabel: 'Send an email', footer: 'by Niklas Brüne', preview: 'Preview · Not for indexing', legal: 'Legal notice (existing website)', privacy: 'Preview privacy notice', privacyTitle: 'Preview privacy notice', privacyText: 'This preview uses no analytics, cookies or embedded third-party media. The local form interface neither sends nor stores entries. GitHub Pages hosts this website and may process technical access data. External websites are opened only when you follow a link. Information sent by email is used to handle your enquiry. Responsible: Niklas Brüne; contact details are provided in the linked legal notice.', githubPrivacy: 'GitHub privacy statement',
    hub: { eyebrow: 'NikVisuals', title: 'Niklas Brüne', intro: 'Website, social media and contact.', website: 'Website', project: 'Discuss a project', socials: 'Social media', gear: 'My gear', contact: 'Contact', phone: 'Phone', legal: 'Legal notice', privacy: 'Privacy' },
  },
};
