export type Language = 'de' | 'en';
export const links = {
 email: 'mailto:info@nikvisuals.de',
 socials: [
  { label: 'LinkedIn', href: 'https://www.linkedin.com/in/niklas-br%C3%BCne-b61877243/' },
  { label: 'Instagram', href: 'https://www.instagram.com/nikvisualsmedia/' },
  { label: 'YouTube', href: 'https://www.youtube.com/@nikvisualsmedia' },
 ],
};
export const content = {
 de: {
  skip: 'Zum Inhalt', menu: 'Menü', close: 'Schließen', language: 'Sprache wählen',
  nav: ['Leistungen', 'Arbeiten', 'Über mich', 'Kontakt'],
  eyebrow: 'Strategisch denken. Pragmatisch machen.', headline: 'AI, Growth & Marketing', headlineEnd: 'für ambitionierte B2B-Unternehmen.',
  intro: 'NikVisuals unterstützt bei ausgewählten Projekten – von Research und Strategie bis zu pragmatischen Workflows, Content-Systemen und Umsetzung mit bestehenden Tools.',
  cta: 'Projekt besprechen', workCta: 'Arbeiten ansehen', heroNote: 'NikVisuals by Niklas Brüne',
  serviceLabel: '01 / Aktuelle Schwerpunkte', serviceTitle: 'Neue Möglichkeiten.\nKonkrete nächste Schritte.',
  services: [
   { name: 'AI & Prozesse', text: 'Wo hilft AI im Arbeitsalltag wirklich? Research, Wissensarbeit und wiederkehrende Prozesse mit vorhandenen Tools sinnvoll verbessern.', tags: ['AI-Use-Cases', 'Research & Wissensarbeit', 'Workflows & Automatisierung'] },
   { name: 'Growth, GTM &\nBusiness Development', text: 'Neue Kunden, Segmente und Märkte systematischer erschließen. Angebote und Go-to-Market-Ansätze validieren, bevor groß investiert wird.', tags: ['Markt- & Wettbewerbsresearch', 'Go-to-Market', 'Business Development'] },
   { name: 'Marketing & Content', text: 'Marketing planbarer machen. Interne Teams, AI und ausgewählte Produktion in einem durchdachten Content-Prozess zusammenbringen.', tags: ['Marketingstrategie', 'Content- & Social-Systeme', 'Ausgewählte Produktion'] },
  ],
  bridgeLabel: 'Praxis trifft Perspektive',
  bridge: 'Selbstständig seit 2021. Dazu das Masterstudium Entrepreneurship & SME Management an der Universität Siegen und aktuell ein Business Exchange an der University of Tulsa. Die heutige Perspektive verbindet Kundenarbeit, akademische Arbeit zu AI im digitalen Marketing und praktische Erfahrung mit AI-Use-Cases und digitalen Prozessen.',
  workLabel: '02 / Bisherige Arbeit', workTitle: 'Ausgewählte\nbisherige Projekte.',
  workIntro: 'Eine Auswahl aus bisherigen Projekten in Media, Content, Workshops und Business Development.',
  artTitles: ['Industrie.\nIm Bild.', 'Wissen.\nWeitergeben.'], aboutAlt: 'Videodreh vor einer Fahrzeugflotte: ein Kameramann filmt eine Gruppe von Mitarbeitenden.',
  video: 'Film auf YouTube ansehen', artwork: 'Typografische Projektvorschau',
  cases: [
   { name: 'LapStore', category: 'Content + Business Development', text: 'Langjährige Zusammenarbeit für Produkt-Content. Später auch Wettbewerbsresearch, B2B-Strategie und Business Development.', image: 'lapstore.jpg', alt: 'Szene aus einem LapStore-Werbevideo: ein Mann mit Smartphone.', video: 'https://www.youtube.com/watch?v=hWaSx8RWAg8', type: 'photo' },
   { name: 'SMS group', category: 'Corporate Media', text: 'Wiederkehrende Corporate-, Industrie- und Eventproduktionen. Komplexe Organisation, teils mit kurzen Lieferzeiten.', image: '', alt: '', video: '', type: 'industrial' },
   { name: 'Stadt Hilchenbach', category: 'Content & Distribution', text: 'Langjährige Drohnen- und Content-Arbeit für Tourismus und Stadtmarketing, ergänzt um Social Media und Distribution. Mit organischer Reichweite und regionaler Medienresonanz.', image: 'hilchenbach.jpg', alt: 'Luftaufnahme von Hilchenbach aus dem NikVisuals-Drohnenfilm.', video: 'https://www.youtube.com/watch?v=5iZrmH-16NY', type: 'photo' },
   { name: 'IHK Siegen', category: 'Workshops', text: 'Praxisnahe Workshops zu Social Media, Content und Smartphone-Video. Wissen, das sich direkt im Arbeitsalltag anwenden lässt.', image: '', alt: '', video: '', type: 'workshop' },
  ],
  aboutLabel: '03 / Der Mensch dahinter', aboutTitle: 'Hi, ich bin Niklas.',
  about: 'Mit Video und digitalen Plattformen hat alles angefangen. Seit 2021 arbeite ich mit NikVisuals selbstständig für B2B- und Unternehmenskunden. Aus der Produktion heraus ist mein Blick breiter geworden: auf Unternehmertum, Marketing, Business Development und den sinnvollen Einsatz von AI. Mein Masterstudium Entrepreneurship & SME Management in Siegen und der aktuelle Business Exchange in Tulsa ergänzen diese Praxis um neue Perspektiven. Mich interessiert, wie aus einer guten Idee ein konkreter nächster Schritt wird – mit klarem Blick auf das Geschäft und Freude an der Umsetzung.',
  aboutCaption: 'Einblick in die bisherige Produktionsarbeit', aboutSignal: 'Auch vorgestellt bei WDR Lokalzeit & Radio Siegen',
  contactLabel: '04 / Kontakt', contactTitle: 'Projekt besprechen', contactText: 'Eine Idee, eine Frage oder eine konkrete Herausforderung? Schreib mir, worum es geht.',
  emailLabel: 'E-Mail schreiben', footer: 'by Niklas Brüne', preview: 'Website-Vorschau · Nicht zur Indexierung', legal: 'Impressum (bestehende Website)', privacy: 'Datenschutz dieser Vorschau', privacyTitle: 'Datenschutz der Vorschau', privacyText: 'Diese Vorschau verwendet keine Analyse-Tools, Cookies, Kontaktformulare oder eingebetteten Drittanbieter-Medien. GitHub Pages stellt die Website bereit und kann technische Zugriffsdaten verarbeiten. Externe Links öffnen erst nach einem Klick die jeweilige Website. Bei Kontakt per E-Mail werden die übermittelten Angaben zur Bearbeitung der Anfrage verwendet. Verantwortlich: Niklas Brüne; Kontaktdaten im verlinkten Impressum.', githubPrivacy: 'Datenschutzerklärung von GitHub',
 },
 en: {
  skip: 'Skip to content', menu: 'Menu', close: 'Close', language: 'Choose language',
  nav: ['Focus', 'Work', 'About', 'Contact'],
  eyebrow: 'Strategic thinking. Practical doing.', headline: 'AI, Growth & Marketing', headlineEnd: 'for ambitious B2B companies.',
  intro: 'NikVisuals supports selected projects – from research and strategy to practical workflows, content systems and implementation with existing tools.',
  cta: 'Discuss a project', workCta: 'Explore the work', heroNote: 'NikVisuals by Niklas Brüne',
  serviceLabel: '01 / Current focus', serviceTitle: 'New possibilities.\nPractical next steps.',
  services: [
   { name: 'AI & Processes', text: 'Where can AI genuinely help at work? Improve research, knowledge work and recurring processes using existing tools.', tags: ['AI use cases', 'Research & knowledge work', 'Workflows & automation'] },
   { name: 'Growth, GTM &\nBusiness Development', text: 'Explore new customers, segments and markets more systematically. Validate offers and go-to-market approaches before investing heavily.', tags: ['Market & competitor research', 'Go-to-market', 'Business development'] },
   { name: 'Marketing & Content', text: 'Make marketing more consistent. Bring internal teams, AI and selected production together in a considered content process.', tags: ['Marketing strategy', 'Content & social systems', 'Selected production'] },
  ],
  bridgeLabel: 'Practice meets perspective',
  bridge: 'Self-employed since 2021. Alongside an M.Sc. programme in Entrepreneurship & SME Management at the University of Siegen and a current business exchange at the University of Tulsa. Today’s perspective combines client work, academic work on AI in digital marketing, and practical experience with AI use cases and digital processes.',
  workLabel: '02 / Previous work', workTitle: 'Selected\nprevious projects.', workIntro: 'A selection of previous projects in media, content, workshops and business development.',
  artTitles: ['Industry.\nIn focus.', 'Knowledge.\nShared.'], aboutAlt: 'Video production in front of a vehicle fleet: a camera operator films a group of staff.',
  video: 'Watch film on YouTube', artwork: 'Typographic project preview',
  cases: [
   { name: 'LapStore', category: 'Content + Business Development', text: 'A long-running product content collaboration. Later also competitor research, B2B strategy and business development.', image: 'lapstore.jpg', alt: 'Scene from a LapStore advertising film: a man using a smartphone.', video: 'https://www.youtube.com/watch?v=hWaSx8RWAg8', type: 'photo' },
   { name: 'SMS group', category: 'Corporate Media', text: 'Repeated corporate, industrial and event productions. Complex coordination, sometimes with short delivery timelines.', image: '', alt: '', video: '', type: 'industrial' },
   { name: 'Stadt Hilchenbach', category: 'Content & Distribution', text: 'Long-running drone and content work for tourism and city marketing, plus social media and distribution. With organic reach and regional media coverage.', image: 'hilchenbach.jpg', alt: 'Aerial view of Hilchenbach from the NikVisuals drone film.', video: 'https://www.youtube.com/watch?v=5iZrmH-16NY', type: 'photo' },
   { name: 'IHK Siegen', category: 'Workshops', text: 'Practical workshops on social media, content and smartphone video. Knowledge participants can apply in their everyday work.', image: '', alt: '', video: '', type: 'workshop' },
  ],
  aboutLabel: '03 / The person behind it', aboutTitle: 'Hi, I’m Niklas.',
  about: 'It started with video and digital platforms. Since 2021, I have worked independently through NikVisuals for B2B and corporate clients. Production gradually broadened my perspective towards entrepreneurship, marketing, business development and practical uses of AI. My master’s studies in Entrepreneurship & SME Management in Siegen and current business exchange in Tulsa bring new perspectives to that experience. I’m interested in turning a good idea into a concrete next step – with a clear understanding of the business and an enjoyment of getting things done.',
  aboutCaption: 'Behind the scenes of previous production work', aboutSignal: 'Also featured on WDR Lokalzeit & Radio Siegen',
  contactLabel: '04 / Contact', contactTitle: 'Discuss a project', contactText: 'An idea, a question or a specific challenge? Tell me what you have in mind.',
  emailLabel: 'Send an email', footer: 'by Niklas Brüne', preview: 'Website preview · Not for indexing', legal: 'Legal notice (existing website)', privacy: 'Preview privacy notice', privacyTitle: 'Preview privacy notice', privacyText: 'This preview uses no analytics, cookies, contact forms or embedded third-party media. GitHub Pages hosts this website and may process technical access data. External websites are opened only when you follow a link. Information sent by email is used to handle your enquiry. Responsible: Niklas Brüne; contact details are provided in the linked legal notice.', githubPrivacy: 'GitHub privacy statement',
 },
};
