export type Video={id:string;title:string;category:{de:string;en:string};summary:{de:string;en:string};thumbnail:string;thumbnailAlt:{de:string;en:string};organization?:string;source:'YouTube oEmbed'};
const make=(id:string,title:string,category:[string,string],summary:[string,string],organization?:string):Video=>({id,title,category:{de:category[0],en:category[1]},summary:{de:summary[0],en:summary[1]},thumbnail:`videos/${id}.webp`,thumbnailAlt:{de:`YouTube-Vorschaubild: ${title}`,en:`YouTube thumbnail: ${title}`},organization,source:'YouTube oEmbed'});
export const videos:Video[]=[
make('njQ9DBAihV8','Imagefilm KMD - Kultureller Marktplatz Dahlbruch | Sport, Jugend & Veranstaltungen in Hilchenbach',['Imagefilm','Corporate film'],['Imagefilm für den Kulturellen Marktplatz Dahlbruch mit Sport-, Jugend- und Veranstaltungsangeboten.','Image film for Kultureller Marktplatz Dahlbruch, featuring sport, youth and event activities.'],'KMD'),
make('WwuJh_wi3dE','Videoproduktion für Unternehmen! Behind the Scenes bei der SMS Group Eröffnungsfeier 🎥',['Behind the Scenes','Behind the scenes'],['Ein Blick hinter die Kulissen einer SMS-group-Eröffnungsfeier.','A behind-the-scenes look at an SMS group opening event.'],'SMS group'),
make('8_4-DPbOR2k','FC Hilchenbach vs Sportfreunde Siegen Aftermovie NikVisuals Media',['Event','Event'],['Aftermovie zum Spiel FC Hilchenbach gegen Sportfreunde Siegen.','Aftermovie from FC Hilchenbach versus Sportfreunde Siegen.'],'FC Hilchenbach'),
make('_0ooFK6AV6M','Reifen Thomas Imagefilm - KFZ-Werkstatt in Hilchenbach',['Imagefilm','Image film'],['Imagefilm für Reifen Thomas, eine KFZ-Werkstatt in Hilchenbach.','Image film for Reifen Thomas, an automotive workshop in Hilchenbach.'],'Reifen Thomas'),
make('BDR6sHFXoiI','Kundenrezension Imagefilm Produktion / Unternehmensfilm Produktion Frank Vorländer',['Kundenfeedback','Client feedback'],['Video-Feedback von Frank Vorländer zur Imagefilm- und Unternehmensfilm-Produktion.','Video feedback from Frank Vorländer on image-film and corporate-film production.'],'Frank Vorländer'),
make('ObgIseEQ0ME','Kundenrezension Stadt Hilchenbach Drohnenfilm & Social Media Produktion',['Kundenfeedback','Client feedback'],['Video-Feedback der Stadt Hilchenbach zu Drohnenfilm und Social-Media-Produktion.','Video feedback from Stadt Hilchenbach on drone film and social-media production.'],'Stadt Hilchenbach'),
make('YhN2u5-05JY','IMMOBILIENVIDEO FERIENHAUS WILDBLUME IN WINTERBERG 4K',['Immobilienvideo','Property video'],['4K-Immobilienvideo für das Ferienhaus Wildblume in Winterberg.','4K property video for Ferienhaus Wildblume in Winterberg.'],'Ferienhaus Wildblume'),
make('oE9I8w93pvc','Kundenrezension Siegerlandcenter Weidenau Imagefilm & Social Media Produktion',['Kundenfeedback','Client feedback'],['Video-Feedback des Siegerland Centers zu Imagefilm und Social-Media-Produktion.','Video feedback from Siegerland Center on image-film and social-media production.'],'Siegerland Center'),
make('-9XjGPp35Ds','Kundenrezension Vesprima Vespaverleih Imagefilm & Social Media Produktion',['Kundenfeedback','Client feedback'],['Video-Feedback von Vesprima zu Imagefilm und Social-Media-Produktion.','Video feedback from Vesprima on image-film and social-media production.'],'Vesprima'),
make('XAmfUMlUiWE','NikVisuals Media WDR Lokalzeit Beitrag und Live Interview vom 23.03.2023 Niklas Brüne',['Presse & Founder','Press & founder'],['WDR-Lokalzeit-Beitrag und Live-Interview mit Niklas Brüne vom 23. März 2023.','WDR Lokalzeit feature and live interview with Niklas Brüne from 23 March 2023.'],'WDR Lokalzeit'),
make('rIf3DnQTIYg','Mein Radio Siegen Interview! NikVisuals Media bei Florian Rubens',['Presse & Founder','Press & founder'],['Interview bei Radio Siegen mit Florian Rubens über NikVisuals Media.','Radio Siegen interview with Florian Rubens about NikVisuals Media.'],'Radio Siegen'),
make('Yam3awPbyO4','So entsteht ein professioneller Video Podcast mit 6 Kameras und Livemusikvideos!',['Behind the Scenes','Behind the scenes'],['Einblicke in die Produktion eines Video-Podcasts mit mehreren Kameras und Livemusikvideos.','A look at producing a video podcast with multiple cameras and live-music videos.']),
make('c9jnXEILfSk','Vesprima - Vespaverleih im Siegerland Imagefilm | NikVisuals Media',['Imagefilm','Image film'],['Imagefilm für Vesprima, einen Vespaverleih im Siegerland.','Image film for Vesprima, a scooter-rental business in the Siegerland region.'],'Vesprima'),
make('WiW-drQkj9U','BMW Isetta Schmiede Imagefilm | Isetta Restauration Werkstatt',['Imagefilm','Image film'],['Imagefilm für eine Werkstatt, die BMW Isetta restauriert.','Image film for a workshop restoring BMW Isettas.'],'BMW Isetta Schmiede'),
make('orSF_UAh60I','Fitnessstudio Aczente Hilchenbach Imagefilm 2022 | NIKVISUALS MEDIA',['Imagefilm','Image film'],['Imagefilm aus dem Jahr 2022 für das Fitnessstudio Aczente in Hilchenbach.','Image film from 2022 for Aczente fitness studio in Hilchenbach.'],'Aczente Hilchenbach'),
make('hXbhESu1Mv8','Vorländer Sanitär Heizung Solar Imagefilm von NikVisuals Media 4K | Hilchenbach Sanitärdienst',['Imagefilm','Image film'],['4K-Imagefilm für Vorländer Sanitär, Heizung und Solar in Hilchenbach.','4K image film for Vorländer Sanitär, Heizung und Solar in Hilchenbach.'],'Vorländer Sanitär Heizung Solar'),
make('WOt-zZXKTBM','Recruitingfilm Schornsteinfegerbetrieb Steffen Kellermann in Kreuztal | NIKVISUALS MEDIA',['Recruiting','Recruiting'],['Recruitingfilm für den Schornsteinfegerbetrieb von Steffen Kellermann in Kreuztal.','Recruiting film for Steffen Kellermann’s chimney-sweep business in Kreuztal.'],'Steffen Kellermann'),
make('5iZrmH-16NY','Hilchenbach am Rothaarsteig VON OBEN! Drohnenaufnahmen',['Drohne & Orte','Drone & places'],['Drohnenaufnahmen von Hilchenbach am Rothaarsteig für Tourismus und Stadtmarketing.','Drone footage of Hilchenbach on the Rothaarsteig for tourism and city marketing.'],'Stadt Hilchenbach'),
make('h7GD0uyyoyQ','【5,4K】AMAZING MALTA CINEMATIC DRONE FOOTAGE - DJI AIR 2S',['Drohne & Orte','Drone & places'],['Cinematic Drone Footage aus Malta, aufgenommen mit einer DJI Air 2S.','Cinematic drone footage from Malta, filmed with a DJI Air 2S.']),
make('SO7sqUkx9pM','Sprengung der Autobahnbrücke A45 Lüdenscheid | Talbrücke Rahmede in NRW 4K UHD mit Drohne Zeitlupe',['Drohne & Orte','Drone & places'],['Drohnen- und Zeitlupenaufnahmen der Sprengung der Talbrücke Rahmede.','Drone and slow-motion footage of the Rahmede viaduct demolition.'],'Talbrücke Rahmede'),
make('jiiriepdEBE','UnArt Coverband LIVE - Kreuztal DonnerstagsIn 2023 - Aftermovie NikVisuals Media',['Event','Event'],['Aftermovie eines UnArt-Coverband-Auftritts bei DonnerstagsIn 2023 in Kreuztal.','Aftermovie of UnArt Coverband at DonnerstagsIn 2023 in Kreuztal.'],'UnArt'),
make('Gkx1ZFXN9kI','Siegerlandcenter Jubiläumswochenende Eventvideo Siegen Weidenau',['Event','Event'],['Eventvideo zum Jubiläumswochenende des Siegerland Centers in Siegen-Weidenau.','Event video from Siegerland Center’s anniversary weekend in Siegen-Weidenau.'],'Siegerland Center'),
make('B1tixD5BTGM','SIC Radio Siegen Flashbackparty Eventvideo',['Event','Event'],['Eventvideo zur SIC Radio Siegen Flashbackparty.','Event video from the SIC Radio Siegen Flashbackparty.'],'SIC Radio Siegen'),
make('Q8rnwmJusQ0','SIC Kindersommerfest 2023 Eventvideo',['Event','Event'],['Eventvideo zum SIC Kindersommerfest 2023.','Event video from the SIC Kindersommerfest 2023.'],'SIC'),
make('XSJKev1qAhM','Cinematic Motocross Show Edit | Canon R5 + Canon RF 24-105mm @SW-MOTECH',['Action & Sport','Action & sport'],['Cinematic Edit einer Motocross-Show mit Material von SW-MOTECH.','Cinematic edit of a motocross show featuring SW-MOTECH.'],'SW-MOTECH'),
make('MSodJRZr4Uw','VW Golf 2 Edersee Tour 2022 #G2FNH - Aftermovie by NikVisuals',['Event','Event'],['Aftermovie einer VW Golf 2 Tour am Edersee im Jahr 2022.','Aftermovie from a VW Golf 2 tour at Edersee in 2022.']),
make('m2sf6etIURs','LEMONAID GETRÄNKE WERBUNG | Charitea Drink Spec AD',['Produkt & Werbung','Product & advertising'],['Spec Ad für LEMONAID und ChariTea als Produkt- und Werbefilm.','Spec ad for LEMONAID and ChariTea as a product and advertising film.'],'LEMONAID / ChariTea'),
make('hWaSx8RWAg8','LapStore: Gebrauchte Laptops versandkostenfrei bestellen.',['Produkt & Werbung','Product & advertising'],['Produktfilm für LapStore rund um gebrauchte Laptops und den Bestellprozess.','Product film for LapStore about refurbished laptops and the ordering process.'],'LapStore'),
make('px-t2uLdcjM','LapStore: Gebrauchte Laptops versandkostenfrei bestellen.',['Produkt & Werbung','Product & advertising'],['Kürzere Produktfilm-Variante für LapStore und gebrauchte Laptops.','Shorter product-film version for LapStore and refurbished laptops.'],'LapStore'),
make('WugwOPGH9Iw','Morpheus 8 Radio-Frequenz + Microneedling Behandlung Erklärvideo',['Erklärvideo','Explainer video'],['Erklärvideo zur Morpheus-8-Behandlung mit Radiofrequenz und Microneedling.','Explainer video about the Morpheus 8 treatment using radiofrequency and microneedling.'],'Morpheus 8'),
make('H3YjnDhKUYQ','LEMONAID LIMETTE COMMERCIAL | Charitea Drink Spec AD',['Produkt & Werbung','Product & advertising'],['Spec Ad für LEMONAID Limette und ChariTea.','Spec ad for LEMONAID Lime and ChariTea.'],'LEMONAID / ChariTea'),
make('WR4BBw6HSGc','SMS group Schwertransport LinkedIn Video',['Corporate','Corporate'],['LinkedIn-Video für SMS group zum Thema Schwertransport.','LinkedIn video for SMS group about heavy transport.'],'SMS group'),
make('8Nb_wHCHVk8','SMS group Campus Eröffnung Aftermovie mit Interviews',['Event','Event'],['Aftermovie mit Interviews zur Eröffnung des SMS-group-Campus.','Aftermovie with interviews from the SMS group campus opening.'],'SMS group')
];
const byId=(id:string)=>videos.find(video=>video.id===id)!;
export const videoSections=[
 {id:'b2b',title:{de:'B2B & Corporate',en:'B2B & corporate'},items:['8Nb_wHCHVk8','WR4BBw6HSGc','WwuJh_wi3dE','hWaSx8RWAg8','hXbhESu1Mv8','WOt-zZXKTBM','_0ooFK6AV6M','WiW-drQkj9U','px-t2uLdcjM','WugwOPGH9Iw'].map(byId)},
 {id:'imagefilm',title:{de:'Imagefilm & Marke',en:'Image films & brands'},items:['c9jnXEILfSk','orSF_UAh60I','YhN2u5-05JY'].map(byId)},
 {id:'orte',title:{de:'Institutionen, Tourismus & Orte',en:'Institutions, tourism & places'},items:['njQ9DBAihV8','5iZrmH-16NY'].map(byId)},
 {id:'feedback',title:{de:'Kundenfeedback',en:'Client feedback'},items:['BDR6sHFXoiI','ObgIseEQ0ME','oE9I8w93pvc','-9XjGPp35Ds'].map(byId)},
 {id:'werbung',title:{de:'Produkt & Werbung',en:'Product & advertising'},items:['m2sf6etIURs','H3YjnDhKUYQ'].map(byId)},
 {id:'event',title:{de:'Event & Community',en:'Events & community'},items:['Gkx1ZFXN9kI','jiiriepdEBE','8_4-DPbOR2k','B1tixD5BTGM','Q8rnwmJusQ0','XSJKev1qAhM','MSodJRZr4Uw'].map(byId)},
 {id:'presse',title:{de:'Presse, Founder & Behind the Scenes',en:'Press, founder & behind the scenes'},items:['XAmfUMlUiWE','rIf3DnQTIYg','Yam3awPbyO4'].map(byId)},
 {id:'drohne',title:{de:'Drohne & besondere Projekte',en:'Drone & special projects'},items:['h7GD0uyyoyQ','SO7sqUkx9pM'].map(byId)}
];
