export const legacyRedirects = [
  { from: '/leistungen-kompetenzen-videoproduktion-unternehmen', to: '/#leistungen' },
  { from: '/portfolio', to: '/#arbeiten' },
  { from: '/kontakt', to: '/#kontakt' },
  { from: '/videoproduktionen-mittelstand-siegen', to: '/videos/' },
  { from: '/karriere', to: '/#praktikum' },
  { from: '/nikvisualsmedia-imagefilme-unternehmen', to: '/videos/' },
  { from: '/recrutingvideos-mittelstand-unternehmen', to: '/videos/' },
  { from: '/produktvideos', to: '/videos/' },
  { from: '/drohnenaufnahmen', to: '/videos/' },
  { from: '/immobilienvideografie', to: '/videos/' },
  { from: '/eventvideoproduktion', to: '/videos/' },
  { from: '/musikvideos', to: '/videos/' },
  { from: '/360gradrundgang3d', to: '/videos/' },
  { from: '/fotos', to: '/#arbeiten' },
  { from: '/werkstudent-foto-video-content', to: '/#praktikum' },
  { from: '/praktikum-bwl', to: '/#praktikum' },
  { from: '/praktikant-video-editing', to: '/#praktikum' },
  { from: '/praktikant-digital-design', to: '/#praktikum' },
  { from: '/praktikant-webdesign', to: '/#praktikum' },
  { from: '/praktikum-business-development', to: '/#praktikum' },
  { from: '/praktikum-sales-support', to: '/#praktikum' },
  { from: '/praktikant-digitales-marketing', to: '/#praktikum' },
  { from: '/praktikant-motion-graphics-und-animation', to: '/#praktikum' },
  { from: '/praktikum-initiativbewerbung', to: '/#praktikum' },
  { from: '/filmmakinggear', to: '/links/' },
];

export const activeRoutes = new Set([
  '/',
  '/en/',
  '/videos/',
  '/en/videos/',
  '/links/',
  '/en/links/',
  '/impressum/',
  '/datenschutz/',
]);
